# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# This captures golden/known-good configurations.
# command example: ansible-playbook --ask-vault-pass pb.collect.golden.configuration.yml --extra-vars "lab=base/ospf/isis/bgp/mh_ospf/mh_isis/mh_bgp"
# Successfully ran on ansible version: ansible 2.4.2.0: ansible-galaxy list Juniper.junos,1.4.3
---
 - name: create golden directory
   hosts: localhost
   gather_facts: no
   tasks:

   - name: create golden directory
     file: 
       path: "{{playbook_dir}}/{{ item }}" 
       state: directory
     with_items: 
      - golden_configuration
      - golden_configuration/base_underlay_evpn_vxlan_overlay
      - golden_configuration/ospf_underlay_evpn_vxlan_overlay
      - golden_configuration/isis_underlay_evpn_vxlan_overlay 
      - golden_configuration/bgp_underlay_evpn_vxlan_overlay 
      - golden_configuration/mh_ospf_underlay_evpn_vxlan_overlay
      - golden_configuration/mh_isis_underlay_evpn_vxlan_overlay
      - golden_configuration/mh_bgp_underlay_evpn_vxlan_overlay

 - name: set and collect junos golden configuration
   hosts: junos-ssh
   connection: local
   gather_facts: no    
   tasks:

    - name: Collect configuration in text format from devices
      junos_facts:
       gather_subset: config
       config_format: text
       provider: "{{ credentials }}"
      register: result_text

    - name: copy collected configuration in golden directory
      copy:
        content: "{{ result_text.ansible_facts.ansible_net_config }}"
        dest: "{{ playbook_dir }}/golden_configuration/{{ lab }}_underlay_evpn_vxlan_overlay/{{ inventory_hostname }}.conf"

