---
loopback: 100.0.0.189
iso_loopback: 49.0001.0001.0001.0189.00
global_asn: 65534
local_asn: 65189
neighbors:
   - interface: et-0/0/0
     name: poc-qfx5110-169
     peer_interface: et-0/0/4
     asn: 65169
     peer_ip: 100.0.0.43 
     local_ip: 100.0.0.42
     peer_loopback: 100.0.0.169
   - interface: et-0/0/1  
     name: poc-qfx5110-170
     peer_interface: et-0/0/4
     asn: 65170
     peer_ip: 100.0.0.45
     local_ip: 100.0.0.44
     peer_loopback: 100.0.0.170
   - interface: et-0/0/2
     name: poc-qfx5110-171
     peer_interface: et-0/0/4
     asn: 65171
     peer_ip: 100.0.0.47
     local_ip: 100.0.0.46
     peer_loopback: 100.0.0.171
directly_connected:
   - dc_interface: xe-0/0/3:0
     dc_name: To_Test_Equipment
     dc_local_ip: 100.189.1.1
     dc_local_ip_mask: 16
